### ISSUE TITLE
Selectable/copyable Tweet text

### ISSUE THREAD

**Issue by ianrenton** [haku/Onosendai#126]
It would be nice if long-pressing on tweet text opened the standard Android Select / Copy controls so that the text could be copied to the clipboard. Currently this gesture causes a bit of a screen flash as if it's thinking about offering these controls, but nothing appears.

This could instead be implemented as part of #122's Share button, as a "Copy to clipboard" option in the Share menu.

**Comment by haku** [comment]
This seems to be fixed by #51.

**Comment by haku** [comment]
Fixed on all my devices.
Closing.
Reopen if still broken.
