### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by haku** [haku/Onosendai#130]
Either add to main F-Droid repo or run own repo.
Own repo seems like a good starting point for testing, etc.

Needs:
- Do something sensible with APK's version number.  Currently its still 1.
- Figure out some https hosting?  Perhaps via heroku?
- Automate pushing stable builds into repo.
- ...
- profi... ohwait.

**Comment by Poussinou** [comment]
@haku I see you have a F-Droid compatible repo [here](https://onosendai.herokuapp.com/). Please feel free to join this [forum](https://forum.f-droid.org/t/known-repositories/721) and add your repo to [this page](https://f-droid.org/wiki/page/Known_Repositories) :)
If one day you manage to build your app without any closed librairies or something like that, push your app to the official F-Droid repo ;)
