### ISSUE TITLE
Link to profiles, etc.

### ISSUE THREAD

**Issue by haku** [haku/Onosendai#142]
Long hold a mention to get a menu:
Link to profile page,
Perhaps follow/unfollow, etc.?
Needs some thought.

**Comment by haku** [comment]
There is no "are you sure?" on the follow/unfollow btn.
Should fix this.

**Comment by ianrenton** [comment]
As it stands, "long press a username item" isn't particularly discoverable - I tried a few different things before I figured out how to trigger it. I don't have a great suggestion for how to improve discoverability, but it's something that IMHO ought to be considered in the future once the functionality is finished.

**Comment by haku** [comment]
ATM that is convenient - its incomplete and somewhat untested.
It is something I want, but very rarely.  So hard to justify effort / find interest.
I have some ideas to make things more Material Design, but dam its a lot of effort.
I do not think MD is /that/ much better that its worth all the code.
And small incremental changes are best.
(I hate "OMG we changed everything" updates)
Plus its taken ages to wrangle my maven build setup to compile against 5.0 APIs. :(

**Comment by ianrenton** [comment]
Fair enough - my few brushes with Android development have been a pain in the arse from start to finish, so I understand that :)

**Comment by haku** [comment]
I could add add/remove form lists, but its quite a lot of code that I will use very rarely.
Will revising this feature later / when someone asks for it.
Closing.
