### ISSUE TITLE
SuccessWhale Changes

### ISSUE THREAD

**Issue by ianrenton** [haku/Onosendai#155]
As you probably know, a few changes are happening in SuccessWhale at the moment. 

The minor issue is that Heroku are no longer going to offer a useful free tier for apps. Given the low request volume I can probably host the SuccessWhale API on my own Web server rather than paying for Heroku. This would mean a URL change at some point in the next few months, and assuming I can get HTTPS sorted out with a virtual host configuration we would need to make sure that OnoSendai supports SNI and has the new certificate pinned. 

The other wider issue is whether SuccessWhale is still useful to OnoSendai. Since we can no longer support Facebook, I'm not sure what SW offers that isn't already done in OS, or would be neater done in OS to avoid people needing a separate SW account. 

What are your thoughts?

**Comment by haku** [comment]
Info dump, will expand later.
Things SW provides:
- feed mixing
- column config for first time install
- (was going to) filter sync
- proxying to hind mobile location from twitter / avoid gov filters
- ...?

**Comment by haku** [comment]
Based on my notes, changing the SW cert baked into an OS build is something like:
```bash
echo | openssl s_client -connect api.successwhale.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | openssl x509 -out remote.crt
openssl x509 -text -in remote.crt
keytool -import -trustcacerts -file remote.crt -alias api.successwhale.com -keystore successwhale.jks
keytool -importkeystore -srckeystore successwhale.jks -destkeystore successwhale.bks \
 -srcstoretype JKS -deststoretype BKS -srcstorepass 123456 -deststorepass 123456 \
 -provider org.bouncycastle.jce.provider.BouncyCastleProvider \
 -providerpath ~/Downloads/bcprov-jdk15on-146.jar
```
The it goes at `/src/main/resources/successwhale.bks`.

**Comment by haku** [comment]
Anything else needed here, or all good for now?

**Comment by ianrenton** [comment]
I think we're good. OS is working fine with the new SW API endpoint.
