### ISSUE TITLE
Notification content in ticker

### ISSUE THREAD

**Issue by ianrenton** [haku/Onosendai#162]
Please consider putting the content of a notification in the "ticker" text as well as the main notification text. (That's the text that briefly appears along the notification bar when the notification first appears.)

When headphones are connected I have my phone read out incoming notifications using TTS, and for most apps the ticker field is the most useful summary to have read out, but OnoSendai does not set this field.

**Comment by haku** [comment]
Any thoughts on what you would like it to say?  What sort of length would be good?
For a column Mentions, could be something like,

For multiple:
"Mentions has 3 new updates."

For single:
"Mentions has a new update."
"Mentions has new update from 0xFae." (not sure TTS will always like handles)
"Mentions has new update from alex." (or full names given the strange chars some people use)
"alex posted $tweet.body" (is this really a good idea?)

Are they "updates", "tweets", "posts", other?

**Comment by ianrenton** [comment]
Does it need to be something new? Using the text that's already used for the notification would be fine!

**Comment by haku** [comment]
Oh, just the `"%d new updates."` that the most basic notification has?

**Comment by ianrenton** [comment]
That would be reasonable - sometimes I get notifications with the full text of the item as well, I think. It could use that full text instead if available?

**Comment by haku** [comment]
Depends on how many new tweets there are,
But even if just one, does it include column title? User name or full name? Hence previous suggestions.
Wondering it it should be geared for showing on screen or reading out via TTS.

**Comment by ianrenton** [comment]
Column might be handy? Whatever real vs username the notifications normally use - I think I see usernames for twitter and full names for Facebook.

It should definitely be tailored for showing on screen. I could be the only person in the world using the ticker text for TTS, certainly the only OS user! I'll deal with any weirdness on the TTS side with Tasker voodoo.

**Comment by haku** [comment]
In which case how about this?:
1 tweet: "$username: $body"
>1 tweets: "$column: $count new updates."

**Comment by ianrenton** [comment]
Works for me!

**Comment by haku** [comment]
Happy with fix?

**Comment by ianrenton** [comment]
Looks good to me!

**Comment by haku** [comment]
Cool!
