### ISSUE TITLE
Skin tone modifiers should not be counted when positioning URLs

### ISSUE THREAD

**Issue by haku** [haku/Onosendai#174]
This tweet https://twitter.com/tintinfp/status/654805685645873153 contains the string:
>💪🏼💪🏼💪🏼

Which in JSON looks like:
```json
"\ud83d\udcaa\ud83c\udffc\ud83d\udcaa\ud83c\udffc\ud83d\udcaa\ud83c\udffc"
```

It should be decoded as 6 characters:
```
\ud83d\udcaa
\ud83c\udffc
\ud83d\udcaa
\ud83c\udffc
\ud83d\udcaa
\ud83c\udffc
```
But then rendered as 3.

Even Twitter's website, which clears knows about skin tone modifiers, renders this wrong, with the modifier as its own block instead of altering the preceding character.
![screenshot from 2015-10-18 22 13 54](https://cloud.githubusercontent.com/assets/502684/10566665/9f172c62-75e5-11e5-8460-ace2345c55b5.png)

The API reports the character offset of the URL as if each `\ud83c\udffc` does not exist, i.e. this is 3 characters long:
```json
"\ud83d\udcaa\ud83c\udffc\ud83d\udcaa\ud83c\udffc\ud83d\udcaa\ud83c\udffc"
```

OS / Android does not know about skin tone modifiers, and does not even seem to know these are unicode characters at all, and thus counts each `\ud83c\udffc` as two characters and positioning the URL 6 characters too far to the left and splatting the preceding text.

**Comment by haku** [comment]
Too add to the fun...
```java
public class A {
  public static void main(String[] args) {
    String a = "💪🏼💪🏼💪🏼";
    System.out.println(a);
    System.out.println(a.length());

    String b = "です";
    System.out.println(b);
    System.out.println(b.length());
  }
}
```
On my desktop (`java version "1.7.0_79"`) outputs:
```
$ java A       
💪🏼💪🏼💪🏼
12
です
2
```
Which is going to make writing a JUnit test for this so much fun.

**Comment by haku** [comment]
May be related: http://stackoverflow.com/a/969200/332868

**Comment by haku** [comment]
How about just gsub'ing the t.co URL?
(Thanks @rvedotrc)

**Comment by stuarthicks** [comment]
Possible occurrence/variation of this issue in [this tweet](https://twitter.com/stuarthicks/status/698806076515479552) which renders correctly on Web and iOS [like this](https://www.dropbox.com/s/nd5spid1ojshg1b/2016-02-14%2017.09.26.png?dl=0) but on Onosendai looks like [this](https://www.dropbox.com/s/6awstitjv735xuk/2016-02-14%2017.08.58.png?dl=0).

**Comment by haku** [comment]
Trying find and replace approach instead of using offset indexes.
And while messing with the same code, made it remote image URLs like Twitter does.

**Comment by haku** [comment]
Seems to be fixed ok.
Closing.
