### ISSUE TITLE
Support Let's Encrypt cert for SuccessWhale

### ISSUE THREAD

**Issue by ianrenton** [haku/Onosendai#175]
At some point over the next month, I would like to change tge certificate used by the https://api.successwhale.com endpoint from my own self-signed cert to one issued by Let's Encrypt.

As I understand it, OnoSendai currently has a pinned certificate (my self signed one). Can this be removed, and Android's own cert trust store be used instead? All versions of Android should now trust certs issued by Let's Encrypt.

**Comment by ianrenton** [comment]
Migration strategy: Currently OnoSendai uses the "api2" subdomain. I have left this one on the normal SSL key and moved the "api" subdomain over to the new key. When you get a chance could you please try using "api" from OnoSendai, relying on Android's trust store.

**Comment by haku** [comment]
Sorry for not replying sooner.
Code changed, seems to work as expected.
(I might have broken it for older versions of Android, but testing/fixing that can wait for now)

**Comment by ianrenton** [comment]
Working for me too. I'm not sure how many SW-via-OS users there are at the moment as I guess neither of us collect that kind of data, but I'd assume it's approximately... One? In which case older versions of Android are unlikely to be a problem.

**Comment by haku** [comment]
I have this old tablet that does not support > 4.0.4 :(

**Comment by ianrenton** [comment]
Ouch, I thought my Flyer & Desire HD were bad being stuck on Jellybean! What breaks OS on older versions of Android, do they implement the certificate storage differently?

**Comment by haku** [comment]
SNI.  I just need to adapt this slightly but CBA last night.
https://github.com/haku/Onosendai/blob/master/src/main/java/com/vaguehope/onosendai/util/TlsSniSocketFactory.java

**Comment by ianrenton** [comment]
Oh yeah, that old chestnut. I forgot about that one!

**Comment by ianrenton** [comment]
With SW being pretty much dead at this point, I'm closing this issue.
