### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by haku** [haku/Onosendai#3]
Local lists of patters can be used to filter tweets from lists.
Apply at fetch time or display time?

**Comment by haku** [comment]
Done a crappy UI to specify some filters.

TODO list, in order:
- Add filtered column to DB.
- Various UI DB reading APIs check filtered field.  Can apply to all calls by default.  Only reapplying filters should need to see previously filtered tweets.
- Implement filter parser and predicate, actually decided how regexes are going to work as I am still undecided, open to suggestions.
- When fetching new tweets, apply filters.
- Button at top of filters page to reapply filters to existing tweets on request.  Tweet object probably gains a boolean field 'filtered'.  Only need to modify DB if filtered state changes and can all be written in one transaction.  Use DB cursor to avoid loading all tweets into memory at once.

SW integration:
- Button at top of filters page to fetch filters from SW.
- Button at top of filters page to push filters to SW? (assuming this is wanted)

Optional:
- Auto reapply filters (as a background task)?
- Auto SW filter sync in background if filters have changed locally?  What if remote filters changed?  How often to check?

**Comment by haku** [comment]
Calling this one done enough for now.
Please raise a new ticket for SW filter sync with how you want it to work.
Closing.

**Comment by ianrenton** [comment]
Done the SW version.

**Comment by haku** [comment]
Sync to SW: issue #152
