### ISSUE TITLE
Standard Holo "toolbar"

### ISSUE THREAD

**Issue by ianrenton** [haku/Onosendai#51]
Consider using the standard Holo-style "toolbar" chrome? (It's probably officially called something other than a toolbar.)

The default appearance of this bar, as used by e.g. the ICS/JB "Settings" app fits OS's design language quite well.

If you want to go down this route, the word "menu" should probably be replaced by the "three vertical dots" icon too.

**Comment by haku** [comment]
```
 11 files changed, 511 insertions(+), 218 deletions(-)
```
Yep, that was, as expected, a silly amount of code that totally vindicates delaying this feature. ^^
As usual, barely tested, etc.

Known thing that might be an issue if anyone suggests a better way:
As there is now only one menu, it can not guess which account you want when "Post" is selected.
So ATM it always pops up to ask (same as if launch triggered by sharing from another app).

Dam, actually I guess it could guess if there is only one column visible (i.e. phone).  Will fix later.

**Comment by haku** [comment]
Perhaps not perfect, but those imperfections were there before.
So scope of this ticket completed.
Pushed to F-Droid repo.
