### ISSUE TITLE
Obey Android global 《Sync Enabled》 flag

### ISSUE THREAD

**Issue by haku** [haku/Onosendai#93]
If user turns 《Sync》 off then OS should stop doing background updates.

**Comment by ianrenton** [comment]
(I have a vague feeling that I've mentioned this on an issue before, so apologies if so.) Lollipop has a batch sync feature to improve battery life, so if you're working on tying OS' sync more tightly into the Android way of doing things, it should probably use this on 5.0+ devices.

**Comment by haku** [comment]
OS has always used `AlarmManager.INTERVAL_FIFTEEN_MINUTES`, "inexact recurrence interval".

This passed to `setInexactRepeating()`:
" As of API 19, all repeating alarms are inexact. Because this method has been available since API 3, your application can safely call it and be assured that it will get similar behavior on both current and older versions of Android."

And all along this API:
"...since the system can adjust alarms' delivery times to cause them to fire simultaneously, avoiding waking the device from sleep more than necessary".

ref: https://developer.android.com/intl/fr/reference/android/app/AlarmManager.html#INTERVAL_FIFTEEN_MINUTES

So, as far as I can tell, its been doing that all along anyway.

On each alarm event, it checks to see what columns have expired and need fetching.

**Comment by haku** [comment]
After digging through https://developer.android.com/intl/fr/training/sync-adapters/index.html ,
might just be as simple as checking `ContentResolver.getMasterSyncAutomatically()`.

**Comment by haku** [comment]
516 days later it turned out to be trivial.
Oh well.
Closing.
